image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        deployment: staging
        script:
          - eval `ssh-agent -s`
          - ssh-add ~/.ssh/id_rsa
          - ssh-add -l
          - cat ./deploy.sh | ssh -T root@dev2.cogniteq.com -p2110
          - echo "Deploy step finished"
