image: php:7.2

pipelines:
  branches:
    develop:
      - step:
          name: Production
          caches:
            - composer
          script:
            - chmod +x ~/.ssh
            - ssh -T root@dev2.cogniteq.com -p2110
            - git pull
