image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        deployment: staging
        script:
          - cat ./deploy.sh | ssh root@dev2.cogniteq.com -p2110
          - echo "Deploy step finished"
